import React, { useState } from 'react';
import { Box, Text, useInput } from 'ink';

export type WelcomeChoice =
  | { type: 'open'; docId: string }
  | { type: 'from-repo' }
  | { type: 'import-file'; path: string }
  | { type: 'write-new' };

interface WelcomeProps {
  onChoice: (choice: WelcomeChoice) => void;
  cwd: string;
}

type Step = 'menu' | 'enter-url' | 'enter-path';

// Generated by: npx figlet-cli "codocs"
const LOGO = [
  "                _                ",
  "   ___ ___   __| | ___   ___ ___ ",
  "  / __/ _ \\ / _` |/ _ \\ / __/ __|",
  " | (_| (_) | (_| | (_) | (__\\__ \\",
  "  \\___\\___/ \\__,_|\\___/ \\___|___/",
];

interface MenuItem {
  icon: string;
  label: string;
  description: string;
}

const MENU_ITEMS: MenuItem[] = [
  {
    icon: '\u25C7', // ◇
    label: 'Open existing',
    description: 'Connect to an existing Google Doc by pasting its URL or document ID. You\u2019ll start listening for comments immediately.',
  },
  {
    icon: '\u2728', // ✨
    label: 'Generate from codebase',
    description: 'An AI agent explores your repository and drafts an initial design document. Great for starting a new project.',
  },
  {
    icon: '\uD83D\uDCE5', // 📥
    label: 'Import local file',
    description: 'Upload a markdown or text file from your filesystem as a new Google Doc.',
  },
  {
    icon: '\u270E', // ✎
    label: 'Write new',
    description: 'Opens your $EDITOR to write a document from scratch. The file is uploaded to Google Docs when you save and quit.',
  },
];

function shortenPath(p: string): string {
  const home = process.env.HOME ?? '';
  if (home && p.startsWith(home)) return '~' + p.slice(home.length);
  return p;
}

function repoName(cwd: string): string {
  return cwd.split('/').pop() ?? cwd;
}

export function Welcome({ onChoice, cwd }: WelcomeProps) {
  const [step, setStep] = useState<Step>('menu');
  const [selected, setSelected] = useState(0);
  const [input, setInput] = useState('');

  useInput((ch, key) => {
    // ── Text input steps ──────────────────────────────────
    if (step === 'enter-url' || step === 'enter-path') {
      if (key.return) {
        if (input.trim()) {
          if (step === 'enter-url') {
            onChoice({ type: 'open', docId: input.trim() });
          } else {
            onChoice({ type: 'import-file', path: input.trim() });
          }
        }
        return;
      }
      if (key.backspace || key.delete) {
        setInput((s) => s.slice(0, -1));
        return;
      }
      if (key.escape) {
        setStep('menu');
        setInput('');
        return;
      }
      if (ch && !key.ctrl && !key.meta) {
        setInput((s) => s + ch);
      }
      return;
    }

    // ── Menu navigation ───────────────────────────────────
    if (key.upArrow || ch === 'k') {
      setSelected((s) => Math.max(0, s - 1));
    } else if (key.downArrow || ch === 'j') {
      setSelected((s) => Math.min(MENU_ITEMS.length - 1, s + 1));
    } else if (key.return) {
      switch (selected) {
        case 0: setStep('enter-url'); break;
        case 1: onChoice({ type: 'from-repo' }); break;
        case 2: setStep('enter-path'); break;
        case 3: onChoice({ type: 'write-new' }); break;
      }
    } else if (ch === 'q' || key.escape) {
      process.exit(0);
    }
  });

  return (
    <Box flexDirection="column" alignItems="center" paddingY={1}>
      {/* Logo */}
      <Box flexDirection="column" alignItems="center" marginBottom={0}>
        {LOGO.map((line, i) => (
          <Text key={i} color="cyan">{line}</Text>
        ))}
      </Box>

      <Text dimColor>Collaborative documents powered by AI agents</Text>

      <Box marginTop={1} marginBottom={1}>
        <Text dimColor>{'─'.repeat(58)}</Text>
      </Box>

      {step === 'menu' && (
        <>
          <Box>
            {/* Left: menu items */}
            <Box flexDirection="column" width={32}>
              {MENU_ITEMS.map((item, i) => {
                const isSelected = i === selected;
                return (
                  <Box key={i} marginBottom={i < MENU_ITEMS.length - 1 ? 1 : 0}>
                    <Text color={isSelected ? 'cyan' : 'gray'}>
                      {isSelected ? '\u25B8 ' : '  '}
                    </Text>
                    <Text color={isSelected ? 'cyan' : 'white'}>
                      {item.icon}
                    </Text>
                    <Text bold={isSelected}>
                      {'  '}{item.label}
                    </Text>
                  </Box>
                );
              })}
            </Box>

            {/* Divider + description */}
            <Box flexDirection="column" marginLeft={1} paddingLeft={2} width={34}
              borderStyle="single" borderTop={false} borderBottom={false} borderRight={false} borderLeft={true}
            >
              <Text dimColor wrap="wrap">{MENU_ITEMS[selected].description}</Text>
            </Box>
          </Box>

          <Box marginTop={1}>
            <Text dimColor>{'─'.repeat(58)}</Text>
          </Box>
          <Box>
            <Text dimColor>repo: </Text>
            <Text>{repoName(cwd)}</Text>
            <Text dimColor>  {'\u00B7'}  cwd: </Text>
            <Text dimColor>{shortenPath(cwd)}</Text>
          </Box>

          <Box marginTop={1}>
            <Text dimColor>
              {'\u2191\u2193'} select  {'\u00B7'}  enter confirm  {'\u00B7'}  q quit
            </Text>
          </Box>
        </>
      )}

      {step === 'enter-url' && (
        <Box flexDirection="column" alignItems="center">
          <Text>Paste a Google Docs URL or document ID:</Text>
          <Box marginTop={1}>
            <Text dimColor>{'> '}</Text>
            <Text>{input}</Text>
            <Text color="cyan">{'\u2588'}</Text>
          </Box>
          <Box marginTop={1}>
            <Text dimColor>esc go back  {'\u00B7'}  enter confirm</Text>
          </Box>
        </Box>
      )}

      {step === 'enter-path' && (
        <Box flexDirection="column" alignItems="center">
          <Text>Path to a markdown file:</Text>
          <Box marginTop={1}>
            <Text dimColor>{'> '}</Text>
            <Text>{input}</Text>
            <Text color="cyan">{'\u2588'}</Text>
          </Box>
          <Box marginTop={1}>
            <Text dimColor>esc go back  {'\u00B7'}  enter confirm</Text>
          </Box>
        </Box>
      )}
    </Box>
  );
}
