import React, { useState, useMemo } from 'react';
import { Box, Text, useInput } from 'ink';
import type { CodocsSession } from '@codocs/db';
import { BUILD_VERSION } from '../../version.js';

export type WelcomeChoice =
  | { type: 'resume'; sessionId: string; docIds: string[]; agentType: string }
  | { type: 'open'; docId: string }
  | { type: 'from-repo' }
  | { type: 'import-file'; path: string }
  | { type: 'write-new' }
  | { type: 'from-prompt'; prompt: string }
  | { type: 'quit' };

interface WelcomeProps {
  onChoice: (choice: WelcomeChoice) => void;
  cwd: string;
  recentSessions?: CodocsSession[];
}

type Step = 'menu' | 'enter-url' | 'enter-path' | 'enter-prompt';

// Generated by: npx figlet-cli "codocs"
const LOGO = [
  "                _                ",
  "   ___ ___   __| | ___   ___ ___ ",
  "  / __/ _ \\ / _` |/ _ \\ / __/ __|",
  " | (_| (_) | (_| | (_) | (__\\__ \\",
  "  \\___\\___/ \\__,_|\\___/ \\___|___/",
];

interface MenuItem {
  icon: string;
  label: string;
  description: string;
}

interface MenuSection {
  title: string;
  items: MenuItem[];
}

interface FlatItem extends MenuItem {
  section: number;
  item: number;
}

const BASE_MENU_SECTIONS: MenuSection[] = [
  {
    title: 'Open existing',
    items: [
      {
        icon: '\uD83C\uDF10', // 🌐
        label: 'Google Docs URL',
        description: 'Connect to an existing Google Doc by pasting its URL or document ID. You\u2019ll start listening for comments immediately.',
      },
      {
        icon: '\uD83D\uDCE5', // 📥
        label: 'Local file',
        description: 'Upload a markdown or text file from your filesystem as a new Google Doc.',
      },
    ],
  },
  {
    title: 'Create new',
    items: [
      {
        icon: '\u2728', // ✨
        label: 'Generate from codebase',
        description: 'An AI agent explores your repository and drafts an initial design document. Great for starting a new project.',
      },
      {
        icon: '\u270F\uFE0F', // ✏️
        label: 'Write in editor',
        description: 'Opens your $EDITOR to write a document from scratch. The file is uploaded to Google Docs when you save and quit.',
      },
      {
        icon: '\uD83D\uDCAC', // 💬
        label: 'Generate from prompt',
        description: 'Describe the document you want and an AI agent will generate it for you.',
      },
    ],
  },
];

function shortenPath(p: string): string {
  const home = process.env.HOME ?? '';
  if (home && p.startsWith(home)) return '~' + p.slice(home.length);
  return p;
}

function repoName(cwd: string): string {
  return cwd.split('/').pop() ?? cwd;
}

/** Check if a string looks like a Google Docs URL or a bare document ID. */
function isValidDocInput(value: string): boolean {
  const trimmed = value.trim();
  if (!trimmed) return false;
  // Google Docs URL
  if (/^(https?:\/\/)?docs\.google\.com\/document\/d\/[a-zA-Z0-9_-]+/.test(trimmed)) return true;
  // Bare document ID (alphanumeric, hyphens, underscores — typically 20-60 chars)
  if (/^[a-zA-Z0-9_-]{10,}$/.test(trimmed)) return true;
  return false;
}

function buildMenuSections(sessions: CodocsSession[]): MenuSection[] {
  if (sessions.length === 0) return BASE_MENU_SECTIONS;

  const resumeSection: MenuSection = {
    title: 'Resume',
    items: sessions.map((s) => {
      const label = s.docTitle ?? s.docIds[0].slice(0, 20) + '...';
      return {
        icon: '\u25B6', // ▶
        label,
        description: `Resume session ${s.id} with ${s.docIds.length} doc${s.docIds.length !== 1 ? 's' : ''} using ${s.agentType} agent.`,
      };
    }),
  };

  return [resumeSection, ...BASE_MENU_SECTIONS];
}

function flattenSections(sections: MenuSection[]): FlatItem[] {
  return sections.flatMap((section, si) =>
    section.items.map((item, ii) => ({ section: si, item: ii, ...item })),
  );
}

export function Welcome({ onChoice, cwd, recentSessions = [] }: WelcomeProps) {
  const [step, setStep] = useState<Step>('menu');
  const [selected, setSelected] = useState(0);
  const [input, setInput] = useState('');

  const menuSections = useMemo(() => buildMenuSections(recentSessions), [recentSessions]);
  const flatItems = useMemo(() => flattenSections(menuSections), [menuSections]);

  // Number of resume items (shifts the base section indices)
  const resumeCount = recentSessions.length > 0 ? recentSessions.length : 0;
  const hasResume = resumeCount > 0;

  useInput((ch, key) => {
    // ── Text input steps ──────────────────────────────────
    if (step === 'enter-url' || step === 'enter-path' || step === 'enter-prompt') {
      if (key.return) {
        const trimmed = input.trim();
        if (!trimmed) return;
        if (step === 'enter-url') {
          if (!isValidDocInput(trimmed)) return; // block invalid input
          onChoice({ type: 'open', docId: trimmed });
        } else if (step === 'enter-path') {
          onChoice({ type: 'import-file', path: trimmed });
        } else {
          onChoice({ type: 'from-prompt', prompt: trimmed });
        }
        return;
      }
      if (key.backspace || key.delete) {
        setInput((s) => s.slice(0, -1));
        return;
      }
      if (key.escape) {
        setStep('menu');
        setInput('');
        return;
      }
      if (ch && !key.ctrl && !key.meta) {
        setInput((s) => s + ch);
      }
      return;
    }

    // ── Menu navigation ───────────────────────────────────
    if (key.upArrow || ch === 'k') {
      setSelected((s) => Math.max(0, s - 1));
    } else if (key.downArrow || ch === 'j') {
      setSelected((s) => Math.min(flatItems.length - 1, s + 1));
    } else if (key.return) {
      const flat = flatItems[selected];

      // Resume section items
      if (hasResume && flat.section === 0) {
        const session = recentSessions[flat.item];
        onChoice({ type: 'resume', sessionId: session.id, docIds: session.docIds, agentType: session.agentType });
        return;
      }

      // Base sections (offset by resume section if present)
      const baseSection = hasResume ? flat.section - 1 : flat.section;
      if (baseSection === 0 && flat.item === 0) setStep('enter-url');
      else if (baseSection === 0 && flat.item === 1) setStep('enter-path');
      else if (baseSection === 1 && flat.item === 0) onChoice({ type: 'from-repo' });
      else if (baseSection === 1 && flat.item === 1) onChoice({ type: 'write-new' });
      else if (baseSection === 1 && flat.item === 2) setStep('enter-prompt');
    } else if (ch === 'q' || key.escape) {
      onChoice({ type: 'quit' });
    }
  });

  return (
    <Box flexDirection="column" alignItems="center" paddingY={1}>
      {/* Logo */}
      <Box flexDirection="column" alignItems="center" marginBottom={0}>
        {LOGO.map((line, i) => (
          <Text key={i} color="cyan">{line}</Text>
        ))}
      </Box>

      <Text dimColor>Collaborative documents powered by AI agents</Text>

      <Box marginTop={1} marginBottom={1}>
        <Text dimColor>{'─'.repeat(58)}</Text>
      </Box>

      {step === 'menu' && (
        <>
          <Box>
            {/* Left: menu items with section headers */}
            <Box flexDirection="column" width={34}>
              {menuSections.map((section, si) => {
                const sectionItems = flatItems.filter((f) => f.section === si);
                return (
                  <Box key={si} flexDirection="column" marginBottom={si < menuSections.length - 1 ? 1 : 0}>
                    <Box marginBottom={0}>
                      <Text dimColor bold>{section.title}</Text>
                    </Box>
                    {sectionItems.map((flat) => {
                      const flatIdx = flatItems.indexOf(flat);
                      const isSelected = flatIdx === selected;
                      const isLast = flat.item === section.items.length - 1;
                      return (
                        <Box key={flatIdx} marginBottom={isLast ? 0 : 0}>
                          <Text color={isSelected ? 'cyan' : 'gray'}>
                            {isSelected ? '  \u25B8 ' : '    '}
                          </Text>
                          <Text color={isSelected ? 'cyan' : 'white'}>
                            {flat.icon}
                          </Text>
                          <Text bold={isSelected}>
                            {'  '}{flat.label}
                          </Text>
                        </Box>
                      );
                    })}
                  </Box>
                );
              })}
            </Box>

            {/* Divider + description */}
            <Box flexDirection="column" marginLeft={1} paddingLeft={2} width={34}
              borderStyle="single" borderTop={false} borderBottom={false} borderRight={false} borderLeft={true}
            >
              <Text dimColor wrap="wrap">{flatItems[selected].description}</Text>
            </Box>
          </Box>

          <Box marginTop={1}>
            <Text dimColor>{'─'.repeat(58)}</Text>
          </Box>
          <Box>
            <Text dimColor>repo: </Text>
            <Text>{repoName(cwd)}</Text>
            <Text dimColor>  {'\u00B7'}  cwd: </Text>
            <Text dimColor>{shortenPath(cwd)}</Text>
          </Box>

          <Box marginTop={1} width={58} justifyContent="space-between">
            <Text dimColor>
              {'\u2191\u2193'} select  {'\u00B7'}  enter confirm  {'\u00B7'}  q quit
            </Text>
            <Text dimColor>v{BUILD_VERSION}</Text>
          </Box>
        </>
      )}

      {(step === 'enter-url' || step === 'enter-path' || step === 'enter-prompt') && (
        <Box flexDirection="column" paddingX={2} width={62}>
          <Text bold>
            {step === 'enter-url' && 'Paste a Google Docs URL or document ID'}
            {step === 'enter-path' && 'Path to a markdown file'}
            {step === 'enter-prompt' && 'Describe the document you want to create'}
          </Text>
          {step === 'enter-url' && (
            <Text dimColor>e.g. https://docs.google.com/document/d/.../edit</Text>
          )}

          <Box marginTop={1} borderStyle="round" borderColor={
            step === 'enter-url' && input.trim() && !isValidDocInput(input)
              ? 'red'
              : 'cyan'
          } paddingX={1}>
            <Text>{input}</Text>
            <Text color="cyan">{'\u2588'}</Text>
          </Box>

          {step === 'enter-url' && input.trim() && !isValidDocInput(input) && (
            <Text color="red">Not a valid Google Docs URL or document ID</Text>
          )}

          <Box marginTop={1}>
            <Text dimColor>esc go back  {'\u00B7'}  enter confirm</Text>
          </Box>
        </Box>
      )}
    </Box>
  );
}
