import React, { useState } from 'react';
import { Box, Text, useInput } from 'ink';

export type WelcomeChoice =
  | { type: 'open'; docId: string }
  | { type: 'from-repo' }
  | { type: 'import-file'; path: string }
  | { type: 'write-new' }
  | { type: 'from-prompt'; prompt: string };

interface WelcomeProps {
  onChoice: (choice: WelcomeChoice) => void;
  cwd: string;
}

type Step = 'menu' | 'enter-url' | 'enter-path' | 'enter-prompt';

// Generated by: npx figlet-cli "codocs"
const LOGO = [
  "                _                ",
  "   ___ ___   __| | ___   ___ ___ ",
  "  / __/ _ \\ / _` |/ _ \\ / __/ __|",
  " | (_| (_) | (_| | (_) | (__\\__ \\",
  "  \\___\\___/ \\__,_|\\___/ \\___|___/",
];

interface MenuItem {
  icon: string;
  label: string;
  description: string;
}

interface MenuSection {
  title: string;
  items: MenuItem[];
}

const MENU_SECTIONS: MenuSection[] = [
  {
    title: 'Open existing',
    items: [
      {
        icon: '\uD83C\uDF10', // 🌐
        label: 'Google Docs URL',
        description: 'Connect to an existing Google Doc by pasting its URL or document ID. You\u2019ll start listening for comments immediately.',
      },
      {
        icon: '\uD83D\uDCE5', // 📥
        label: 'Local file',
        description: 'Upload a markdown or text file from your filesystem as a new Google Doc.',
      },
    ],
  },
  {
    title: 'Create new',
    items: [
      {
        icon: '\u2728', // ✨
        label: 'Generate from codebase',
        description: 'An AI agent explores your repository and drafts an initial design document. Great for starting a new project.',
      },
      {
        icon: '\u270F\uFE0F', // ✏️
        label: 'Write in editor',
        description: 'Opens your $EDITOR to write a document from scratch. The file is uploaded to Google Docs when you save and quit.',
      },
      {
        icon: '\uD83D\uDCAC', // 💬
        label: 'Generate from prompt',
        description: 'Describe the document you want and an AI agent will generate it for you.',
      },
    ],
  },
];

/** Flat list of all selectable items with their section index and item index. */
const FLAT_ITEMS = MENU_SECTIONS.flatMap((section, si) =>
  section.items.map((item, ii) => ({ section: si, item: ii, ...item })),
);

function shortenPath(p: string): string {
  const home = process.env.HOME ?? '';
  if (home && p.startsWith(home)) return '~' + p.slice(home.length);
  return p;
}

function repoName(cwd: string): string {
  return cwd.split('/').pop() ?? cwd;
}

export function Welcome({ onChoice, cwd }: WelcomeProps) {
  const [step, setStep] = useState<Step>('menu');
  const [selected, setSelected] = useState(0);
  const [input, setInput] = useState('');

  useInput((ch, key) => {
    // ── Text input steps ──────────────────────────────────
    if (step === 'enter-url' || step === 'enter-path' || step === 'enter-prompt') {
      if (key.return) {
        if (input.trim()) {
          if (step === 'enter-url') {
            onChoice({ type: 'open', docId: input.trim() });
          } else if (step === 'enter-path') {
            onChoice({ type: 'import-file', path: input.trim() });
          } else {
            onChoice({ type: 'from-prompt', prompt: input.trim() });
          }
        }
        return;
      }
      if (key.backspace || key.delete) {
        setInput((s) => s.slice(0, -1));
        return;
      }
      if (key.escape) {
        setStep('menu');
        setInput('');
        return;
      }
      if (ch && !key.ctrl && !key.meta) {
        setInput((s) => s + ch);
      }
      return;
    }

    // ── Menu navigation ───────────────────────────────────
    if (key.upArrow || ch === 'k') {
      setSelected((s) => Math.max(0, s - 1));
    } else if (key.downArrow || ch === 'j') {
      setSelected((s) => Math.min(FLAT_ITEMS.length - 1, s + 1));
    } else if (key.return) {
      const { section, item } = FLAT_ITEMS[selected];
      if (section === 0 && item === 0) setStep('enter-url');
      else if (section === 0 && item === 1) setStep('enter-path');
      else if (section === 1 && item === 0) onChoice({ type: 'from-repo' });
      else if (section === 1 && item === 1) onChoice({ type: 'write-new' });
      else if (section === 1 && item === 2) setStep('enter-prompt');
    } else if (ch === 'q' || key.escape) {
      process.exit(0);
    }
  });

  return (
    <Box flexDirection="column" alignItems="center" paddingY={1}>
      {/* Logo */}
      <Box flexDirection="column" alignItems="center" marginBottom={0}>
        {LOGO.map((line, i) => (
          <Text key={i} color="cyan">{line}</Text>
        ))}
      </Box>

      <Text dimColor>Collaborative documents powered by AI agents</Text>

      <Box marginTop={1} marginBottom={1}>
        <Text dimColor>{'─'.repeat(58)}</Text>
      </Box>

      {step === 'menu' && (
        <>
          <Box>
            {/* Left: menu items with section headers */}
            <Box flexDirection="column" width={34}>
              {MENU_SECTIONS.map((section, si) => {
                const sectionItems = FLAT_ITEMS.filter((f) => f.section === si);
                return (
                  <Box key={si} flexDirection="column" marginBottom={si < MENU_SECTIONS.length - 1 ? 1 : 0}>
                    <Box marginBottom={0}>
                      <Text dimColor bold>{section.title}</Text>
                    </Box>
                    {sectionItems.map((flat) => {
                      const flatIdx = FLAT_ITEMS.indexOf(flat);
                      const isSelected = flatIdx === selected;
                      const isLast = flat.item === section.items.length - 1;
                      return (
                        <Box key={flatIdx} marginBottom={isLast ? 0 : 0}>
                          <Text color={isSelected ? 'cyan' : 'gray'}>
                            {isSelected ? '  \u25B8 ' : '    '}
                          </Text>
                          <Text color={isSelected ? 'cyan' : 'white'}>
                            {flat.icon}
                          </Text>
                          <Text bold={isSelected}>
                            {'  '}{flat.label}
                          </Text>
                        </Box>
                      );
                    })}
                  </Box>
                );
              })}
            </Box>

            {/* Divider + description */}
            <Box flexDirection="column" marginLeft={1} paddingLeft={2} width={34}
              borderStyle="single" borderTop={false} borderBottom={false} borderRight={false} borderLeft={true}
            >
              <Text dimColor wrap="wrap">{FLAT_ITEMS[selected].description}</Text>
            </Box>
          </Box>

          <Box marginTop={1}>
            <Text dimColor>{'─'.repeat(58)}</Text>
          </Box>
          <Box>
            <Text dimColor>repo: </Text>
            <Text>{repoName(cwd)}</Text>
            <Text dimColor>  {'\u00B7'}  cwd: </Text>
            <Text dimColor>{shortenPath(cwd)}</Text>
          </Box>

          <Box marginTop={1}>
            <Text dimColor>
              {'\u2191\u2193'} select  {'\u00B7'}  enter confirm  {'\u00B7'}  q quit
            </Text>
          </Box>
        </>
      )}

      {step === 'enter-url' && (
        <Box flexDirection="column" alignItems="center">
          <Text>Paste a Google Docs URL or document ID:</Text>
          <Box marginTop={1}>
            <Text dimColor>{'> '}</Text>
            <Text>{input}</Text>
            <Text color="cyan">{'\u2588'}</Text>
          </Box>
          <Box marginTop={1}>
            <Text dimColor>esc go back  {'\u00B7'}  enter confirm</Text>
          </Box>
        </Box>
      )}

      {step === 'enter-path' && (
        <Box flexDirection="column" alignItems="center">
          <Text>Path to a markdown file:</Text>
          <Box marginTop={1}>
            <Text dimColor>{'> '}</Text>
            <Text>{input}</Text>
            <Text color="cyan">{'\u2588'}</Text>
          </Box>
          <Box marginTop={1}>
            <Text dimColor>esc go back  {'\u00B7'}  enter confirm</Text>
          </Box>
        </Box>
      )}

      {step === 'enter-prompt' && (
        <Box flexDirection="column" alignItems="center">
          <Text>Describe the document you want to create:</Text>
          <Box marginTop={1}>
            <Text dimColor>{'> '}</Text>
            <Text>{input}</Text>
            <Text color="cyan">{'\u2588'}</Text>
          </Box>
          <Box marginTop={1}>
            <Text dimColor>esc go back  {'\u00B7'}  enter confirm</Text>
          </Box>
        </Box>
      )}
    </Box>
  );
}
